### ISSUE TITLE
Reports 0.0.4.2 issues

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#104]
- 1 ) When /bal, i have bad output

![capture](https://cloud.githubusercontent.com/assets/4788317/20112889/6031fc4a-a5ee-11e6-8d58-1a4b59f46af4.PNG)

My config:

config.yml
```
Core:
  UUID: true
  Multiworld: false
  Balance: 200.0
...
  Currency:
    Format: <symbol><major><decimal><minor><shorten>
    Conversion: 1.0
    Symbol: $
    Decimal: .
    ItemCurrency: false
    ItemMajor: GOLD_INGOT
    ItemMinor: IRON_INGOT
    MajorName:
      Single: Dollar
      Plural: Dollars
    MinorName:
      Single: Cent
      Plural: Cents
```
world.yml:
```
  world:
    ChangeFee: 10.0
    Balance: 777.0
    Shorten: true
    ShareAccounts: false
    ShareWorld: WorldName
    Currency:
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Livres
        Plural: Livres
      MinorName:
        Single: Cent
        Plural: Cents
```
I'm in world "world". Should have 200 livres or 777 livres ??

- 2 ) When /pay

![capture](https://cloud.githubusercontent.com/assets/4788317/20113152/7413000a-a5ef-11e6-9274-a22dcb386b0d.PNG)

Please download this test server and make some tests yourself with plugins i'm using.

Dropbox: 20 Mo  https://www.dropbox.com/s/528fb5l5g9fdmhh/Spigot_Test_Server_1.10.2.zip?dl=0

Thanks!
