### ISSUE TITLE
Problem with currency format

### ISSUE THREAD

**Issue by Eredrim** [TheNewEconomy/TNE-Bukkit#111]
Hello,

I meet some problems with currency format since the last version (alpha 5.0) : 
This is my currency configuration : 
```
    Currency:
      Format: <symbol><major><decimal><minor>
      Conversion: 1.0
      Symbol: £
      Decimal: .
      ItemCurrency: false
      ItemMajor: 266
      ItemMinor: 265
      MajorName:
        Single: Pound
        Plural: Pounds
      MinorName:
        Single: Penny
        Plural: Pence
```
When I type /money, this is the result : 
>You currently have £200 Pounds.0 Pence

Normally, I would simply have 
>You currently have £200.0
