### ISSUE TITLE
Cannot pay

### ISSUE THREAD

**Issue by sigmasoldi3r** [TheNewEconomy/TNE-Bukkit#146]
## What happens
When issuing the command `/pay someone 1` or `/money pay someone 1` the server says that I cannot afford, but the truth is that I have 200 in my wallet (`/bal` reveals that)

![The image](https://i.gyazo.com/3c4164b3bb9931a38c809055b9ee8024.png)

## Permissions
I've setted up a group named `citizens` which I belong with money (Some) permissions:
```YAML
  citizens:
    inheritance:
    - default
    options:
      prefix: citizen
    permissions:
    - tne.auction
    - tne.bank
    - tne.bank.*
    - tne.use
    - tne.use.*
    - tne.place
    - tne.place.*
    - tne.shop
    - tne.shop.*
    - -tne.shop.admin
    - tne.pin.*
    - tne.money
    - tne.money.pay
```

Maybe resetting the database solves the problem, not sure (I'm pretty new to bukkit/spigot plugins).

## Platform
**Spigot** server for `Minecraft 1.11.2` running under `Windows 10 amd64`

### Other issues
Maybe is somehow related to this: When issuing the command `balancetop` in server console gives me back this:
```
[11:51:16 INFO]: =========[Economy Top]========= 1/1
[11:51:16 INFO]: DyaMetR has 250.0
[11:51:16 INFO]: DyaMetR has 200.0
[11:51:16 INFO]: sigmasoldier has 200.0
[11:51:16 INFO]: null has 0.0
```
Which is a problem because the player `DyaMetR` is duplicated. Tried `tne purge` and `tne reload all` but with no success (Also tried reloading the server).

Let me know if I can provide more info!
