### ISSUE TITLE
Crash when trying to use 1.16 items

### ISSUE THREAD

**Issue by obj-obj** [TheNewEconomy/TNE-Bukkit#446]
#### What is the issue/bug you're experiencing?
When I try to add 1.16 items to the `items.yml` file, the plugin crashes when loading.
#### How can the issue be reproduced?(i.e. the steps to make the issue occur again)
Add the data below to `items.yml`:
```
NETHERITE_INGOT:

    Sign: "tne.item.netherite_ingot.sign"

    #The permission node required to buy this item
    Buy: "tne.item.netherite_ingot.buy"

    #The permission node required to sell this item
    Sell: "tne.item.netherite_ingot.sell"

    #The names supported by shop signs
    Names:
    - "Netherite"
    - "Netherite Ingot"

NETHERITE_BLOCK:

    Sign: "tne.item.netherite_block.sign"

    #The permission node required to buy this item
    Buy: "tne.item.netherite_block.buy"

    #The permission node required to sell this item
    Sell: "tne.item.netherite_block.sell"

    #The names supported by shop signs
    Names:
    - "NetheriteBlock"
    - "Netherite Block"
```
#### TNE version?(exact version number), and whether or not you've made modification to it.
1.1.9.3, no modifications
#### TNE build?(/tne build), and whether or not you've made modification to it.
0.1.1.9d, no modifications
#### Modules Loaded?(exact version number), and whether or not you've made modification to it.
No modules
#### Spigot/Bukkit version?
Paper 276
#### Is your server run in online mode?
Yes
#### The exact command you ran w/ arguments?
`java -Xmx5G -jar server.jar -nogui`
#### config.yml?(use http://paste.ubuntu.com, and remove your SQL details)
https://paste.ubuntu.com/p/CyzBDStN23/
#### Your latest server log file?(use http://paste.ubuntu.com)
Accidentally deleted the log, although I saved the only error from TNE
https://paste.ubuntu.com/p/TkGkqKBCvS/
#### If this is to do with messages/world/player configurations, please include the YAML file for such.(use http://paste.ubuntu.com)

Note: If, for any reason, you elect not to use the following format for your issue, it will be closed without
notice.
