### ISSUE TITLE
Some Bug/Missing feature

### ISSUE THREAD

**Issue by Oruss7** [TheNewEconomy/TNE-Bukkit#80]
- Each server start/Stop, config files is **reset** with default values (sometimes **erease my config** !)

When i update config.yml, i restart my server and old config is set ='( 
(Do not save in-memory to file when stop server !)

- No one commands working with **console** ?!

- Can't **import** essentials account ! Balance is set to initial as config.yml describ it ='(

- Put **enable/disable** mobs/objects/etc in config.yml

- multi-world config: **more one shared world**? [world_the_end, world_nether] are not supported ?!

- add symbol instead of name ($/£/€)
Add to config possibility to **choose name or symbol**: $10.50 or 10,50€ or 10 euros and 50 Cents

- mysql: **add last player name** (for information only ^^)

- flat file: do not serialize but **use yaml/json**. We need to have readeable file please =)

- Add command **/money substract** (you forgot it ?)

- Add **world** parameters to all admin commands (/money give <player> <amount> <world>)

That's all ! Thanks you for you work ! Your plugin will be the reference soon =D

**Comment by creatorfromhell** [comment]
Each server start/Stop, config files is reset with default values (sometimes erease my config !)
- This is a known issue, but will be changed in Alpha 4.0 with the inclusion of an in-game command to change the configuration value

No one commands working with console ?!
- A lot of the console commands have been cut back on.

Can't import essentials account ! Balance is set to initial as config.yml describ it ='(
- Not sure about this one as I haven't used Essentials in a long while, but I'll look into it.

Put enable/disable mobs/objects/etc in config.yml
- These are in their respective files. More or less a question of convience I suppose.
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/mobs.yml#L12
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/objects.yml#L13
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/objects.yml#L36

multi-world config: more one shared world? [world_the_end, world_nether] are not supported ?!
- The shared world configuration was meant to be implemented under each world's configuration.
- i.e. something like this is allowed

```
  world_the_nether:
        
        #Whether or not you want this world to share accounts with another
        ShareAccounts: true
        
        #The world to share accounts with if ShareAccounts is true
        ShareWorld: World
		
  world_the_end:
        
        #Whether or not you want this world to share accounts with another
        ShareAccounts: true
        
        #The world to share accounts with if ShareAccounts is true
        ShareWorld: World
```

add symbol instead of name ($/£/€)
Add to config possibility to choose name or symbol: $10.50 or 10,50€ or 10 euros and 50 Cents
- This is a planned feature

mysql: add last player name (for information only ^^)
- not sure why this would be needed for what TNE is concerned with.

flat file: do not serialize but use yaml/json. We need to have readeable file please =)
- JSON/YAML for data saving would be super inefficient, and a waste of file storage

Add command /money substract (you forgot it ?)
- See /money take
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/commands/money/MoneyTakeCommand.java

Add world parameters to all admin commands (/money give )
- already happened
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/commands/money/MoneyTakeCommand.java#L62
- https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/src/com/github/tnerevival/commands/money/MoneyGiveCommand.java#L62
